language: node_js
dist: trusty
node_js:
  - 11
cache:
  directories:
    - node_modules
before_install:
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - brew install libuv-dev gcc
