language: node_js
node_js:
  - 0.12
  - 4.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - GPP_BINARY=g++-4.8
before_script: bash scripts/get-libuv.sh
